env:
  global:
    - CC_TEST_REPORTER_ID=9a092aa88feed0b0fb7f62c8b6bf4e218c4b055f92bc0bf59342d9a2a8c58a15
language: python
python: "2.7"
install:
  - pip install -r requirements.txt
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - pytest
  - pytest --cov=src tests/
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
